version: '3.8'

services:

  app:
    build: .
    container_name: eai-listing-service
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - eai-internal

  mysql:
    image: mysql:8
    container_name: eai-mysql
    restart: always
    environment:
      MYSQL_DATABASE: eai_listing_service
      MYSQL_ROOT_PASSWORD: root
    networks:
      - eai-internal

networks:
  eai-internal:
    driver: bridge
    internal: false